### PR TITLE
license info for scripture pane

### PR DESCRIPTION
**Pull request by mandolyte**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/14)

### CODE REVIEW

**Comment by mandolyte** [comment]
@RoyalSix Thanks... I'll remove the console log and comment. If the license does not exist the opened tab will show an 404, but it does take you to the repo; just not to the license file.

Note: I am using these previews to share intermediate results. In theory, I have a few more resource types to do the same way.

**Comment by RoyalSix** [comment]
@mandolyte Ahh ok, let me know when this one is ready for review :+1:

**Comment by klappy** [comment]
___
*[src/components/license/License.js, line 10 at r4](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/14#-M5hgNMB4QhyK8sr4SmI:-M5hgNMB4QhyK8sr4SmJ:bo07oc4) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/4758df1d612e74cc126b27bcecf0858a28dce83d/src/components/license/License.js#L10)):*
> ```JavaScript
> export const License = ({
>   rights,
>   licenseLink,
> ```

did you mean to pass style in here?

also, maybe iconProps so they can override the defaults for the icon?

**Comment by klappy** [comment]
___
*[src/components/license/License.js, line 20 at r4](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/14#-M5hge1K3cxM-UibzhCP:-M5hge1K3cxM-UibzhCQ:bg8j6ns) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/4758df1d612e74cc126b27bcecf0858a28dce83d/src/components/license/License.js#L20)):*
> ```JavaScript
>     color: "primary",
>     fontSize: "small",
>     onClick: onClickLicense,
> ```

```
  let _iconProps = {
    color: "primary",
    fontSize: "small",
    onClick: onClickLicense,
    ...iconProps
  };
```

**Comment by mandolyte** [comment]
@klappy changed per above. Not sure how adding `style` to the function argument list helps if it isn't used in the body anywhere. Do I need to add somewhere else?

Code now looks like this (relevant parts only):
```
export const License = ({
  rights,
  licenseLink,
  style,
  iconProps,
}) => {

// skip some code here

  let _iconProps = {
    color: "primary",
    fontSize: "small",
    onClick: onClickLicense,
    ...iconProps,
  };

  let rightsIcon = <Tooltip title={rights} arrow><InfoOutlinedIcon {..._iconProps} /></Tooltip> ; 
```

**Comment by mandolyte** [comment]
> > _[Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/14)_ status: all files reviewed, 6 unresolved discussions (waiting on @mandolyte)
> 
> _[src/components/parallel-scripture/ParallelScripture.js, line 44 at r5](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/14#-M5zkmd2Eo6z0Nu8xPQ1:-M5zkmd2Eo6z0Nu8xPQ2:b-bzvfqj) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/647c93cf01ef0e3b20b8ded0710c3e5c04e66298/src/components/parallel-scripture/ParallelScripture.js#L44)):_
> 
> > ```js
> >           ;
> >           
> >           let rightsIcon = <License rights={rights} licenseLink={licenseLink} />
> > ```
> 
> In this usage of the license, the end css uses 1.25rem for the output. This looks way to big and somehow shifted up. When I used the browser console to edit the css, setting it to 1em looks more appropriate.

I think I found what you identified (I edited the value to match what you described):
```
.MuiSvgIcon-fontSizeSmall {
    font-size: 1em;
}
```
However, I don't know how to alter this value within my code. I'll do some searching and see if I can figure it out.

**Comment by mandolyte** [comment]
@klappy 
This seems to work:
```
  let _iconProps = {
    color: "primary",
    fontSize: "small",
    onClick: onClickLicense,
    style: {
      fontSize: '1em'
    },
    ...iconProps,
  };
```

Thoughts?

**Pull request merged**
