### PR TITLE
Resources context: onAddResourceLink

### PR DESCRIPTION
**Pull request by ancientTexts-net**
separated tracking for **general** resource link and link with **bookId** appended

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/34)

### CODE REVIEW

**Comment by ancientTexts-net** [comment]
Retracting

**Comment by ancientTexts-net** [comment]
OK this is good

**Comment by ancientTexts-net** [comment]
@RoyalSix  ready

**Comment by ancientTexts-net** [comment]
THANK YOU @royalsix  -- that was a deprecated method that should have been removed.
Removed!

Great catch

**Comment by ancientTexts-net** [comment]
___
*[src/components/parallel-scripture/ColumnsMenu.js, line 22 at r3](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/34#-MAbpiDd0xqP0me1ZX3h:-MAbtjHl9KIQ77e6Mg1s:bprgs00) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/204695f0ea0d44bd5780366819ee729b121ae12f/src/components/parallel-scripture/ColumnsMenu.js#L22)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

@ancienttexts-net Looks like this variable `resourceUrl` is missing
</blockquote></details>

Great catch.  that was an unused method (deprecated) that should have been removed.
Good one

**Comment by RoyalSix** [comment]
Looking good so far! I just had one issue when testing

I did the following steps and it resulted in having two blank panes 
image

1. Add the resource by url `Door43-Catalog/hi/ulb/master/3jn`
2. Remove it with the remove button next to the resource
3. Add another resource with url `STR/hi/irv/master/3jn`
4. Scroll on the pane and should see the above screen shot

Note: It looks like the remove button shows after step 2 on a resource that should be static. Not sure if that is related to the bug

@ancientTexts-net

**Comment by ancientTexts-net** [comment]
___
*[src/components/parallel-scripture/ColumnsMenu.js, line 22 at r3](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/34#-MAbpiDd0xqP0me1ZX3h:-MAbu2MH2uQVc7hr5sPc:b-896fix) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/204695f0ea0d44bd5780366819ee729b121ae12f/src/components/parallel-scripture/ColumnsMenu.js#L22)):*
<details><summary><i>Previously, ancientTexts-net (Zach Pennington) wrote…</i></summary><blockquote>

Great catch.  that was an unused method (deprecated) that should have been removed.
Good one
</blockquote></details>

Done.

**Comment by ancientTexts-net** [comment]
___
*[src/components/parallel-scripture/ColumnsMenu.js, line 22 at r3](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/34#-MAbpiDd0xqP0me1ZX3h:-MAbvKjCB5ROiLacoj4X:b-3q3ywv) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/204695f0ea0d44bd5780366819ee729b121ae12f/src/components/parallel-scripture/ColumnsMenu.js#L22)):*
<details><summary><i>Previously, ancientTexts-net (Zach Pennington) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OH actually that is the `TextField` `id`

**Pull request closed without merging**
