### PR TITLE
Bug Fix For Zero Width Joiner In Selections

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/12)

### CODE REVIEW

**Comment by klappy** [comment]
___
*[src/core/selections/selections.js, line 472 at r1](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/12#-M4zMw8eELimgusqMGFq:-M4zMw8f0Xm4767EFdI9:bcid1jo) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/f67ff0af3f3204ef0ac290f9f6ad0ae9fbceb05e/src/core/selections/selections.js#L472)):*
> ```JavaScript
> export const normalizeString = _string => {
>   let string = _string.slice(0);
>   string = string.replace(/\s+/g, ' ').replace(/\u200B/g,'');;
> ```

To keep parity with tC and all of the other apps, my gut tells me we should address this in the tokenizer library somehow and then let all apps update with a known working approach.

**Comment by klappy** [comment]
What is the root issue here and what is the approach to fix it? Is it a short term or long term fix?

**Comment by klappy** [comment]
It looks like the issue was created and discussed in the Greek when changing to invalid text, it breaks and is unable to go back to a functional highlighting state. I'm curious as to how this Ruth test helps?

**Comment by RoyalSix** [comment]
@klappy My mistake. I added a fix for some of the Hebrew highlighting here.

**Comment by RoyalSix** [comment]
@klappy Removing the normalization fixes here. Also adding the original normalization to the string punctation tokenizer. Non safe methods are not enabled by default.

**Comment by klappy** [comment]
___
*[src/core/selections/selections.js, line 479 at r2](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/12#-M5hcuEDEETc5vUA7vi3:-M5hcuEDEETc5vUA7vi4:b2r0x04) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/706840cf5be3f50d030067dbad06738ae128c84e/src/core/selections/selections.js#L479)):*
> ```JavaScript
> export const removePunctuation = _string => {
>   let string = _string.slice(0);
>   string = string.replace(/[.,\/#!$%\^&\*;:{}=\-_`~()]/g, "");
> ```

`tokenize({text: string, greedy: true, normalize: true}).join(' ');`

**Pull request merged**
