### PR TITLE
Error handling for AddResource

### PR DESCRIPTION
**Pull request by ancientTexts-net**
## Describe what your pull request addresses

- [ ]

## Test Instructions

- [ ]

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/93)

### CODE REVIEW

**Comment by mandolyte** [comment]
@ancientTexts-net The first demo work on the parallel scripture page works fine. But the second doesn't do anything and the third crashes. Probably just some fixes to the demo markdown files would correct this.

**Comment by mandolyte** [comment]
*[a discussion](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/93#-MX84qLOEW6sOU0wQtMW:-MX84qLPA9n_qe-_R_dn:b-z8tsx7) (no related file):*
@ancienttexts-net Once an invalid resource is attempted and the error message is shown, the error message stays. So when you click on the versions menu again, the field is blank, but the error message is still there.

I think there is a state that needs to be cleared or something.

---

**Review by mandolyte — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/93)* status: all files reviewed, 1 unresolved discussion (waiting on @ancientTexts-net and @PhotoNomad0)

**Comment by ancientTexts-net** [comment]
*[a discussion](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/93#-MX84qLOEW6sOU0wQtMW:-MXexlWy4L_y5NOhKnIv:b-896fix) (no related file):*
<details><summary><i>Previously, mandolyte wrote…</i></summary><blockquote>

@ancienttexts-net Once an invalid resource is attempted and the error message is shown, the error message stays. So when you click on the versions menu again, the field is blank, but the error message is still there.

I think there is a state that needs to be cleared or something.
</blockquote></details>

Done.

---

**Pull request merged**
