### PR TITLE
Fixes for quote highlighting in single-scripture-rcl

### PR DESCRIPTION
**Pull request by mannycolon**
- Now exporting verse objects helper functions

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/77)

### CODE REVIEW

**Comment by BincyJ** [comment]
@mannycolon does this need to go into 1.1.0? or is it just part of 2.0?

**Comment by mannycolon** [comment]
@BincyJ These changes are part of 2.0

**Comment by BincyJ** [comment]
@mannycolon this looks like a PR. Can you connect it to a related issue. @birchamp I wonder why this is showing up in the tC Create workspace.Should be reflecting in the 2.0.0 workspace. Can you check?

**Comment by mannycolon** [comment]
@BincyJ This isn't connected because I don't have access to the tcc 2.0 Zenhub workspace from this repo

**Comment by mandolyte** [comment]
@mannycolon altho there are a lot of files changed in this PR I only found two "real" changes. All the rest were formatting changes. Am I missing something?

The two changes I found were:
ScriptureTable.js where the parameter "theme" was added:
const useStyles = makeStyles((theme) => ({

src/core/index.js where this line exporting helper functions was added:
export * from './selections/verseObjects';

**Comment by mandolyte** [comment]
@mannycolon one more question... there have been other changes made to the components used by tc-create 1.x for create 2.0.

Do we need to be concerned about backward compatibility?

**Comment by mannycolon** [comment]
@mandolyte Yes, as I mentioned in the PR description, the only real change is that the verse objects helper functions are exported now.

**Comment by mannycolon** [comment]
@mandolyte As long as the major version number has been changed whenever there's a breaking change then there shouldn't be any problems with backward compatibility

**Review by mandolyte — APPROVED** [review]
@mannycolon altho there are a lot of files changed in this PR I only found two "real" changes. All the rest were formatting changes. Am I missing something?

The two changes I found were:
ScriptureTable.js where the parameter "theme" was added:
const useStyles = makeStyles((theme) => ({

src/core/index.js where this line exporting helper functions was added:
export * from './selections/verseObjects';

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/77#-:-MShKQxH1etgeHAf_Y3F:bmee9tb)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

**Pull request merged**
