### PR TITLE
Fix occurrence -1; added some unit tests.

### PR DESCRIPTION
**Pull request by ancientTexts-net**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/54)

### CODE REVIEW

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/54)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @ancientTexts-net, @mandolyte, @mannycolon, @PhotoNomad0, and @RoyalSix)

___
*[src/core/selections/selections.spec.js, line 200 at r1](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/54#-MJSd-KY4UBRvn8lHTZw:-MJSd-KY4UBRvn8lHTZx:b-jbyfzq) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/0d6081d3cc53b4da6aa735b857f18decea4c8541/src/core/selections/selections.spec.js#L200)):*
> ```JavaScript
> 
>   it('should return second occurrence for the given text', () => {
>     debugger;
> ```

Debugger here

**Review by RoyalSix — COMMENTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/54)* status: all files reviewed, 1 unresolved discussion (waiting on @ancientTexts-net, @mandolyte, @mannycolon, and @PhotoNomad0)

**Comment by ancientTexts-net** [comment]
@RoyalSix - Thank you.  Updated after review

**Review by RoyalSix — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/54)* status: all files reviewed, 1 unresolved discussion (waiting on @ancientTexts-net, @mandolyte, @mannycolon, and @PhotoNomad0)

**Review by RoyalSix — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mandolyte, @mannycolon, and @PhotoNomad0)

**Review by RoyalSix — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mandolyte, @mannycolon, and @PhotoNomad0)

**Review by RoyalSix — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/54#-:-MJYXxtG26GIQaCkZ1hC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mandolyte, @mannycolon, and @PhotoNomad0)

**Comment by RoyalSix** [comment]
@ancientTexts-net Once merge conflicts resolved it is ready! 👍🏾

**Pull request merged**
