### PR TITLE
Enhancement klappy hooks contexts

### PR DESCRIPTION
**Pull request by klappy**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20)

### CODE REVIEW

**Comment by klappy** [comment]
___
*[styleguide.config.js, line 18 at r3](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8R_JyNBO7PygUYbKnQ:-M8R_JyNBO7PygUYbKnR:b-m7uicb) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/378a912575a01d100180442a1a5ddaba49cb978b/styleguide.config.js#L18)):*
> ```JavaScript
>       const componentNames = [
>         'Resource.context',
>         'Resources.context',
> ```

@mandolyte How difficult would it be to add examples of a use case that use the custom hooks variants, `useResource` and `useResources`?
I think the Gitea React Toolkit has examples for Hooks as well as Contexts.

**Comment by klappy** [comment]
___
*[src/components/parallel-scripture/ParallelScripture.md, line 71 at r3](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8Rb1TnCGR24hqEBDjv:-M8Rb1TnCGR24hqEBDjw:b8pi6rp) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/378a912575a01d100180442a1a5ddaba49cb978b/src/components/parallel-scripture/ParallelScripture.md#L71)):*
> ```Markdown
>     return (
>         <ParallelScripture 
>           resources={resources} 
> ```

I don't think we need to pass resources here now that the ParallelScripture component consumes the context.

**Comment by klappy** [comment]
___
*[src/components/parallel-scripture/ParallelScripture.md, line 110 at r3](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8RbUHf93Xn5ph7d3op:-M8RbUHf93Xn5ph7d3oq:bxas9xw) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/378a912575a01d100180442a1a5ddaba49cb978b/src/components/parallel-scripture/ParallelScripture.md#L110)):*
> ```Markdown
>   config={config}
> >
>   <Component config={config} resourceLinks={resourceLinks} />
> ```

Now that `resourcesLinks` and `config` are being passed into the Context, we don't need to pass them here.

**Comment by klappy** [comment]
___
*[src/components/parallel-scripture/ParallelScripture.md, line 15 at r3](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8Rbo_f-DpJFZv9uqKw:-M8Rbo_f-DpJFZv9uqKx:b-jtq4pq) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/378a912575a01d100180442a1a5ddaba49cb978b/src/components/parallel-scripture/ParallelScripture.md#L15)):*
> ```Markdown
> import useEffect from 'use-deep-compare-effect';
> 
> function Component( {config, resourceLinks} ) {
> ```

Are we using `config` and `resourceLinks` in the component or just in the ParallelScripture component? If so we can remove them.

**Comment by klappy** [comment]
___
*[src/components/parallel-scripture/ParallelScripture.md, line 79 at r3](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8Rc-teATZkcluflatC:-M8Rc-teATZkcluflatD:b-jtq4pq) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/378a912575a01d100180442a1a5ddaba49cb978b/src/components/parallel-scripture/ParallelScripture.md#L79)):*
> ```Markdown
>         />
>     );
>   }, [resourceLinks, config, bookId, chapter, verse, quote, occurrence]);
> ```

Are we using `config` and `resourceLinks` in the component or just in the ParallelScripture component? If so we can remove them.

**Comment by mandolyte** [comment]
@klappy asked:

> How difficult would it be to add examples of a use case that use the custom hooks variants, useResource and useResources? I think the Gitea React Toolkit has examples for Hooks as well as Contexts.

Looking at GRT, there no such examples for: `useStyles`, `useAuthentication`, `useFile`, `useRepository` (has an empty markdown file).

There is something for `useOrganization` - I can take a look at that one. Only one I saw.

**Comment by mandolyte** [comment]
@klappy I added a demo for the `useResources` custom hook. However I added it to an existing demo page, namely, `ResourcesContext.md`. This is because Styleguidist complains that `useReources.js` does not export a component. I tried and failed some other approaches, but just including it in the existing demo page worked OK.

**Comment by klappy** [comment]
___
*[src/components/selections/helpers.js, line 63 at r4](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8kVGaODvRJcXnoQpw9:-M8kVGaODvRJcXnoQpwA:b-9bbrfb) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/1b9b98fd8779e6395b8d98624c76ef17b1bc568b/src/components/selections/helpers.js#L63)):*
> ```JavaScript
>   _selections.forEach(selection => {
>     //if (selections.includes(_s)) selected = true;
>     let _s;
> ```

We try to avoid abbreviations when possible and err on the side of being explicit. I would recommend calling this `_selection`.
Another way we could even do this is to deconstruct it.  To do this we can do it at the forEach above.

**Comment by klappy** [comment]
___
*[src/components/selections/helpers.js, line 58 at r4](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8kYJmu7AL7sfO2rzpZ:-M8kYJmu7AL7sfO2rzp_:bjiw79s) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/1b9b98fd8779e6395b8d98624c76ef17b1bc568b/src/components/selections/helpers.js#L58)):*
> ```JavaScript
> };
> 
> export const areSelected = ({ words, selections }) => {
> ```

I'm having a hard time reading this method and keeping things straight as to what is what... 
What do you think of the following approach that is explicit and doesn't mix forEach with for loops?

```js
export const areSelected = ({ words, selections }) => {
  let selected = false;
  const selectionsFromWords = words.map(word => selectionFromWord(word));
  selectionsFromWords.forEach( {
    text: textFromWord, occurrence: occurrenceFromWord, occurrences: occurrencesFromWord
  } => {
    selections.forEach({ text, occurrence, occurrences } => {
      // if the loop has already produced a true, we don't want to mark it false. Hence only changing if the condition is true.
      if ( text === textFromWord && occurrence === occurrenceFromWord && occurrences === occurrencesFromWord) selected = true;
    }; 
  });
  return selected;
};
```

**Comment by klappy** [comment]
___
*[src/components/selections/useSelections.js, line 37 at r4](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8kaRbY9Lkvsn00504a:-M8kaRbY9Lkvsn00504b:bbap1fh) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/1b9b98fd8779e6395b8d98624c76ef17b1bc568b/src/components/selections/useSelections.js#L37)):*
> ```JavaScript
> 
>   const update = useCallback((_selections) => {
>     // the "parsify" function is expecting an array of stringified objects
> ```

Because we are now able to use `useDeepCompareEffect` and it's sibling `useDeepCompareCallback` we should be able to pass in arrays of objects without needing to use `parsify` and `stringify`.

**Comment by klappy** [comment]
___
*[src/components/selections/useSelections.js, line 7 at r4](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8kalxxBuRS9zHpIggc:-M8kalxxBuRS9zHpIggd:b-3c93ti) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/1b9b98fd8779e6395b8d98624c76ef17b1bc568b/src/components/selections/useSelections.js#L7)):*
> ```JavaScript
> 
> //import helpers, {parsify, selectionsFromQuote, quoteFromVerse} from './helpers';
> import helpers, { selectionsFromQuote, quoteFromVerse } from './helpers';
> ```

Lets deconstruct the helpers so we don't have to call them with `helpers.function`?

**Comment by klappy** [comment]
___
*[src/components/selections/useSelections.js, line 37 at r4](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8kaRbY9Lkvsn00504a:-M8kb1izEWwEHQz5jKc6:b-t4y5u) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/1b9b98fd8779e6395b8d98624c76ef17b1bc568b/src/components/selections/useSelections.js#L37)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Because we are now able to use `useDeepCompareEffect` and it's sibling `useDeepCompareCallback` we should be able to pass in arrays of objects without needing to use `parsify` and `stringify`.
</blockquote></details>

The reason those were created was to deal with the React memoization not dealing with object comparisons in the arrays.

**Comment by klappy** [comment]
___
*[src/components/usfm/Usfm.context.md, line 1 at r4](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8kbNHI4QKzl8pcNeFI:-M8kbNHI4QKzl8pcNeFJ:bl8cu9g) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/1b9b98fd8779e6395b8d98624c76ef17b1bc568b/src/components/usfm/Usfm.context.md#L1)):*
> ```Markdown
> ```js
> ```

Can we give an example of the hook usage here?

**Comment by klappy** [comment]
___
*[src/components/usfm/Usfm.context.md, line 1 at r4](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8kbNHI4QKzl8pcNeFI:-M8kbWaMAt42ZjvMPuvi:b-ew4v18) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/1b9b98fd8779e6395b8d98624c76ef17b1bc568b/src/components/usfm/Usfm.context.md#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Can we give an example of the hook usage here?
</blockquote></details>

NVM you have an explicit demo already :)

**Comment by klappy** [comment]
___
*[src/components/selections/helpers.js, line 58 at r4](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8kYJmu7AL7sfO2rzpZ:-M8kbwOy1ksCjLwmen2Z:bmv9sic) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/1b9b98fd8779e6395b8d98624c76ef17b1bc568b/src/components/selections/helpers.js#L58)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'm having a hard time reading this method and keeping things straight as to what is what... 
What do you think of the following approach that is explicit and doesn't mix forEach with for loops?

```js
export const areSelected = ({ words, selections }) => {
  let selected = false;
  const selectionsFromWords = words.map(word => selectionFromWord(word));
  selectionsFromWords.forEach( {
    text: textFromWord, occurrence: occurrenceFromWord, occurrences: occurrencesFromWord
  } => {
    selections.forEach({ text, occurrence, occurrences } => {
      // if the loop has already produced a true, we don't want to mark it false. Hence only changing if the condition is true.
      if ( text === textFromWord && occurrence === occurrenceFromWord && occurrences === occurrencesFromWord) selected = true;
    }; 
  });
  return selected;
};
``` 
</blockquote></details>

Notice that I removed the parsify/stringify usage so that we can try to make this work without it.
That will require some changes to the `useSelections.js` custom hook.

**Comment by klappy** [comment]
___
*[src/components/selections/useSelections.js, line 7 at r4](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8kalxxBuRS9zHpIggc:-M8piWyI36Nzy62kzSpw:b-3ttjtp) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/1b9b98fd8779e6395b8d98624c76ef17b1bc568b/src/components/selections/useSelections.js#L7)):*
<details><summary><i>Previously, mandolyte wrote…</i></summary><blockquote>

How about the opposite? There are 7 of them! Right now there is a mix - two are deconstructed and the others are not. The thing I don't like about deconstruction of imported functions is that you can't tell where the function comes from (unless you scroll back to the top and search thru the imports). Deconstructed functions appear to be part of the file you are looking at but are not. A bit confusing to have some many ways to do the same thing... thoughts?
</blockquote></details>

That makes sense. I'm on board with that for now. We should explore it with the team and see what makes sense long term.

**Comment by klappy** [comment]
___
*[src/components/selections/useSelections.js, line 37 at r4](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/20#-M8kaRbY9Lkvsn00504a:-M8pij_s7bKx0-giGEzt:b1gxq37) ([raw file](https://github.com/unfoldingword/scripture-resources-rcl/blob/1b9b98fd8779e6395b8d98624c76ef17b1bc568b/src/components/selections/useSelections.js#L37)):*
<details><summary><i>Previously, mandolyte wrote…</i></summary><blockquote>

Was not aware of "useDeepCompareCallback" -- do you want me to go thru the code base and switch over to it?
</blockquote></details>

I just realized that that does not exist. What I walked Zach through was to pass all props into the callback, and not use any external props in the array at the end. Right now we only have onSelections which is safe and there is no objects which are not safe. There doesn't seem to be a need here.

**Comment by klappy** [comment]
:lgtm:

**Pull request merged**
